version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

  app_file_handler:
    class: logging.FileHandler
    level: INFO
    formatter: standard
    filename: app.log

  debug_file_handler:
    class: logging.FileHandler
    level: DEBUG
    formatter: standard
    filename: debug_output.txt

loggers:
  app_logger:
    level: INFO
    handlers: [console, app_file_handler]
    propagate: no

  debug_logger:
    level: DEBUG
    handlers: [debug_file_handler]
    propagate: no

root:
  level: DEBUG
  handlers: [console]
